#!/bin/bash
cd ~
DIR=".qtum"
if [ -d "$DIR" ]
then
  qtum-cli stop
  sleep 2
  echo "Updating the Qtum Wallet"
  sudo su -c "apt update && apt install —only-upgrade qtum"
  qtumd -daemon
else
  wget -qO - http://repo.qtum.info/apt/public.key | sudo apt-key add -
  sudo su -c "echo 'deb http://repo.qtum.info/apt/raspbian/ stretch main' >> /etc/apt/sources.list"
  sudo apt update && sudo apt install qtum
  qtumd -daemon
fi
