#!/bin/bash
latest_release() {
    curl --silent "https://api.github.com/repos/$1/releases/latest" |
      grep '"tag_name":' |
      sed -E 's/.*"([^"]+)".*/\1/' |
      head -n 1
}
latest_ui() {
    curl --silent "https://api.github.com/repos/rpiwalletui/qtum-ui/releases/latest" |
      grep '"browser_download_url":' |
      sed -E 's/.*"([^"]+)".*/\1/' |
      head -n 1
}

UILATEST="$(latest_release "rpiwalletui/qtum-ui")"
QTUMLATEST="$(latest_release "qtumproject/qtum")"
QTUMDIR=".qtum"
HOST="$(hostname)"
DLLATEST="$(latest_ui)"

cd ~
rm qtum-full.tar.gz
rm -rf qtum-ui
sudo apt-get update && sudo apt-get install -y python3-pip libv4l-dev libopenjp2-7 libopenjp2-7-dev libtiff5
mkdir ~/qtum-ui
echo "Downloading Qtum-Ui..........."
wget -O qtum-ui.tar.gz $DLLATEST -q --show-progress
echo "Installing........."
tar --strip 1 -C ~/qtum-ui -xf ~/qtum-ui.tar.gz
rm qtum-ui.tar.gz
cd  ~/qtum-ui
./qtum-install
pip3 install --upgrade -r requirements.txt
cd ~/qtum-ui
qtumd -daemon
sleep 30
python3 app.py &
clear
echo "///////////////////////////////////////////////////////////////////////"
echo "// The Qtum Pi UI is now starting......                              //"
echo "//                                                                   //"
echo "// Join us on Telegram https://t.me/joinchat/FvYLc1FTsk6qg_wuN9WF8A  //"
echo "//                                                                   //"
echo "// View the source code https://github.com/rpiwalletui/qtum-ui       //"
echo "//                                                                   //"
echo "// Latest Qtum Pi UI Version "$UILATEST"                              //"
echo "//                                                                   //"
echo "// Latest Qtum Wallet "$QTUMLATEST"                      //"
echo "//                                                                   //"
echo "// Contact: trevsadev@protonmail.com                                 //"
echo "//                                                                   //"
echo "// The Qtum UI is now running at http://"$HOST":3404             //"
echo "///////////////////////////////////////////////////////////////////////"
