#!/bin/bash
cd ~
DIR="~/qtum-ui"
if [ -d "$DIR" ]
then
  echo Qtum-Ui Already Installed
  echo If you wish to make a new install delete the qtum-ui directory and try again.
else
  sudo apt-get update
  sudo apt-get install -y python3-pip libv4l-dev libopenjp2-7 libopenjp2-7-dev libtiff5
  mkdir ~/qtum-ui
  echo Downloading Qtum-Ui
  wget https://github.com/rpiwalletui/qtum-ui/releases/download/qtum-piui-0.2.1-beta/qtum-piui-0.2.2-beta.tar.gz
  echo Installing...
  tar --strip 1 -C ~/qtum-ui -xf ~/qtum-piui-0.2.2-beta.tar.gz
  rm qtum-piui-0.2.2-beta.tar.gz
  pip3 install flask Flask-WTF Flask-QRcode Flask-Bootstrap
  cd  ~/qtum-ui
  python3 app.py &
  sleep 3
  echo The UI is now starting.
  echo to stop the UI "type pkill -9 python3"
fi
